name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-run:
    runs-on: self-hosted

    steps:
      - name: Say Hello
        run: echo "🎉 Runner đang hoạt động! oke212"

